### ISSUE TITLE
TODO list of embellishing the representation

### ISSUE THREAD

**Issue by thsno02** [thsno02/voice-conversion#37]
- [ ] ~add guide text;~
- [ ] ~resize the QR code to fit the screen;~
- [ ] ~resize the GUI window;~
- [ ] ~relocate the GUI window into the center;~
- [x] disable the print information.

**Comment by thsno02** [comment]
+ Don't add the guide text, since `pillow` does not render Chinese characters properly;
